theme: jekyll-theme-primer

exclude:
  - node_modules
  - "**/node_modules"
  - vendor
  - "**/vendor"
  - .bundle
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.lock
  - "**/*.log"
  - rag/rag-ubiq/node_modules
  - "**/CHANGELOG.md"
  - "**/*.md"
  - "**/README.md"
